/**
 * esami-info.js — per ogni esame: cos'è, a cosa serve e quali sono i valori di riferimento e ottimali.
 * Sono indicazioni generali e indicative: il riferimento che conta è quello scritto sul tuo referto (cambia da laboratorio a laboratorio),
 * e l'interpretazione spetta sempre al medico.
 *   cos  = cos'è e cosa fa · ott = valori di riferimento / ottimali · nota = cosa può voler dire se è fuori (facoltativa)
 */
export const INFO = {
  'Leucociti': { cos: 'I globuli bianchi: le cellule di difesa del sangue, combattono infezioni e infiammazioni.', ott: 'In genere 4–10 (×10⁹/L). Valori stabili nel tempo sono il segnale migliore.', nota: 'Salgono con infezioni, stress e fumo; scendono con alcune infezioni virali o farmaci.' },
  'Emoglobina': { cos: 'La proteina dei globuli rossi che trasporta l\'ossigeno.', ott: 'Uomo adulto circa 13,5–17,5 g/dL (135–175 g/L).', nota: 'Bassa: possibile anemia (ferro, B12, perdite). Alta: disidratazione, fumo, altitudine.' },
  'Piastrine': { cos: 'Le cellule che servono alla coagulazione del sangue.', ott: 'In genere 150–400 (×10⁹/L).', nota: 'Valori molto bassi o molto alti vanno valutati dal medico.' },
  'VES': { cos: 'Velocità di eritrosedimentazione: un indice generico di infiammazione.', ott: 'Uomo giovane, sotto circa 15–25 mm/h a seconda del laboratorio.', nota: 'È aspecifica: da sola non dice la causa.' },
  'Glicemia': { cos: 'Lo zucchero nel sangue a digiuno: l\'energia che circola.', ott: 'A digiuno 70–99 mg/dL è normale; 100–125 è alterata; da 126 in su va confermata dal medico.', nota: 'La glicemia da sola non basta: HbA1c e insulina completano il quadro.' },
  'Urea': { cos: 'Scarto delle proteine, eliminato dai reni.', ott: 'Circa 15–50 mg/dL.', nota: 'Sale con poca acqua, molte proteine o problemi ai reni.' },
  'Creatinina': { cos: 'Scarto dei muscoli, filtrato dai reni: serve a valutare la funzione renale.', ott: 'Uomo circa 0,7–1,3 mg/dL; dipende dalla massa muscolare (più muscoli o creatina → un po\' più alta).' },
  'eGFR': { cos: 'Stima di quanto sangue filtrano i reni ogni minuto.', ott: 'Da 90 in su (mL/min/1,73 m²) è nella norma; tra 60 e 89 è una lieve riduzione che, senza altri segni di danno renale, non è una malattia.' },
  'Acido urico': { cos: 'Scarto delle purine; in eccesso può dare gotta e calcoli.', ott: 'Uomo circa 3,5–7,0 mg/dL; per prevenire la gotta si punta sotto 6.' },
  'Colesterolo totale': { cos: 'Un grasso necessario a cellule e ormoni; il totale somma HDL, LDL e altre frazioni.', ott: 'Come indicazione generale sotto 190–200 mg/dL, ma conta più il rapporto tra LDL e HDL e il rischio complessivo.' },
  'Colesterolo HDL': { cos: 'Il colesterolo "buono": porta il colesterolo in eccesso verso il fegato.', ott: 'Uomo: oltre 40 mg/dL; meglio 50–60 o più. Si alza con attività aerobica, meno grasso addominale, meno zuccheri raffinati e non fumando.' },
  'Colesterolo LDL': { cos: 'Il colesterolo "cattivo": si deposita nelle pareti delle arterie.', ott: 'Dipende dal rischio: sotto 116 mg/dL se basso, sotto 100 se moderato, sotto 70 se alto, sotto 55 se molto alto (linee guida europee). Il medico decide il tuo obiettivo.' },
  'Trigliceridi': { cos: 'I grassi del sangue, legati a zuccheri, alcol e peso.', ott: 'Sotto 150 mg/dL a digiuno; per il cuore molti puntano sotto 100.', nota: 'Salgono con zuccheri e alcol, soprattutto se il prelievo non è a digiuno.' },
  'AST (GOT)': { cos: 'Enzima di fegato, muscoli e cuore.', ott: 'Uomo circa sotto 35–40 U/L.', nota: 'Sale anche dopo allenamenti intensi (muscoli), con alcol o fegato grasso.' },
  'ALT (GPT)': { cos: 'Enzima soprattutto del fegato: indicatore di salute epatica.', ott: 'Circa sotto 40–50 U/L; per il fegato grasso molti puntano sotto 30–35.' },
  'GGT': { cos: 'Enzima di fegato e vie biliari, sensibile ad alcol e farmaci.', ott: 'Circa sotto 60–70 U/L; più è bassa, meglio.' },
  'Fosfatasi alcalina': { cos: 'Enzima di ossa e vie biliari.', ott: 'Circa 40–130 U/L.' },
  'LDH': { cos: 'Enzima presente in molti tessuti: indicatore generico di danno cellulare.', ott: 'Circa 120–250 U/L (dipende dal metodo).', nota: 'Sale dopo sforzi intensi.' },
  'Lipasi': { cos: 'Enzima del pancreas che digerisce i grassi.', ott: 'Circa 12–60 U/L (dipende dal laboratorio).', nota: 'Un lieve rialzo isolato spesso non è significativo: va letto dal medico.' },
  'Sodio': { cos: 'Minerale che regola acqua e pressione.', ott: '135–146 mmol/L.' },
  'Potassio': { cos: 'Minerale per muscoli e cuore.', ott: '3,5–5,1 mmol/L (dipende dal laboratorio).' },
  'Calcio': { cos: 'Minerale di ossa, muscoli e nervi.', ott: 'Circa 8,5–10,5 mg/dL.' },
  'Magnesio': { cos: 'Minerale per muscoli, nervi, sonno e glicemia.', ott: 'Circa 1,6–2,6 mg/dL.' },
  'Ferro': { cos: 'Il ferro che circola nel sangue (sideremia): cambia molto nella giornata.', ott: 'Circa 65–175 µg/dL; si legge insieme alla ferritina.' },
  'Ferritina': { cos: 'Le tue riserve di ferro.', ott: 'Uomo circa 30–300 ng/mL.', nota: 'Sotto 30: riserve basse. Molto alta: infiammazione o accumulo di ferro.' },
  'Bilirubina totale': { cos: 'Pigmento che nasce dai globuli rossi vecchi e viene smaltito dal fegato.', ott: 'Circa 0,3–1,2 mg/dL.' },
  'Proteina C reattiva': { cos: 'Un marcatore di infiammazione.', ott: 'Nei referti standard "sotto 4–10 mg/L". Per il cuore serve la versione ad alta sensibilità (hs-CRP): sotto 1 mg/L rischio basso, 1–3 medio, sopra 3 alto.', nota: 'Va misurata lontano da infezioni o infiammazioni recenti.' },
  'HbA1c': { cos: 'Emoglobina glicata: la glicemia media degli ultimi 2–3 mesi.', ott: 'Sotto 5,7% (39 mmol/mol) è normale; 5,7–6,4% prediabete; da 6,5% diabete (da confermare).' },
  'Insulina': { cos: 'L\'ormone che fa entrare lo zucchero nelle cellule.', ott: 'A digiuno circa 2–25 mU/L secondo il laboratorio; per la salute metabolica si punta sotto circa 10.' },
  'HOMA': { cos: 'Indice di resistenza all\'insulina, calcolato da glicemia e insulina a digiuno.', ott: 'Sotto circa 2,5 (alcuni puntano sotto 2); sopra suggerisce insulino-resistenza.' },
  'Microalbuminuria': { cos: 'Piccole quantità di albumina nelle urine: segnale precoce di stress di reni e vasi.', ott: 'Sotto 30 mg/g di creatinina; il tuo laboratorio indica sotto 9 come ideale.' },
  'TSH': { cos: 'L\'ormone dell\'ipofisi che regola la tiroide.', ott: 'Circa 0,4–4,0 mUI/L (il laboratorio indica il suo intervallo).', nota: 'Alto: tiroide "pigra"; basso: tiroide "troppo attiva".' },
  'FT3': { cos: 'L\'ormone tiroideo attivo (T3 libero).', ott: 'Circa 2,0–4,4 pg/mL.' },
  'FT4': { cos: 'L\'ormone tiroideo (T4 libero), la riserva che si trasforma in T3.', ott: 'Circa 7,6–18 pg/mL.' },
  'Vitamina A': { cos: 'Serve a vista, pelle e difese.', ott: 'Circa 30–80 µg/dL secondo il laboratorio.', nota: 'Valori alti possono derivare da integratori.' },
  'Vitamina B12': { cos: 'Serve a sangue e nervi; si trova negli alimenti animali.', ott: 'Oltre circa 300–400 pg/mL è rassicurante; sotto 200 è carenza.' },
  'Vitamina C': { cos: 'Antiossidante, serve al collagene e all\'assorbimento del ferro.', ott: 'Secondo il laboratorio circa 4,6–14,9 mg/L.' },
  'Vitamina D': { cos: 'Serve a ossa, muscoli e difese; si produce con il sole.', ott: '30–100 ng/mL sufficiente; 20–30 insufficiente; sotto 20 carenza.' },
  'ACTH': { cos: 'L\'ormone dell\'ipofisi che stimola il cortisolo.', ott: 'Al mattino circa 8–47 pg/mL.' },
  'Cortisolo': { cos: 'L\'ormone dello stress, con un picco al mattino.', ott: 'Al mattino circa 5–23 µg/dL.', nota: 'Dipende molto dall\'orario e dallo stress del prelievo.' },
  'Testosterone totale': { cos: 'Il principale ormone maschile: muscoli, energia, umore.', ott: 'Uomo adulto circa 2–7 ng/mL secondo il laboratorio.', nota: 'Ha un picco al mattino e varia con età, sonno e peso.' },
  'Zinco': { cos: 'Minerale per difese, pelle e ormoni.', ott: 'Circa 60–140 µg/dL.' },
  'Calprotectina fecale': { cos: 'Un segnale di infiammazione dell\'intestino.', ott: 'Sotto 50 µg/g normale; 50–120 dubbio; sopra 120 positivo.' },
  'Transglutaminasi IgA': { cos: 'Anticorpi cercati nella diagnosi della celiachia.', ott: 'Sotto 10 UI/mL è negativo (con IgA totali normali).' },
  'Omocisteina': { cos: 'Un aminoacido legato a cuore e vitamine del gruppo B.', ott: 'Meglio sotto 10–12 µmol/L; fino a 15 rientra nella norma di laboratorio.' },
};
